### ISSUE TITLE
Elegant Circles icons

### ISSUE THREAD

**Issue by dohliam** [VectorLogoZone/git-svg-icons#1]
**Name of the site**: Elegant Circles

**Website or home page URL**: https://dohliam.github.io/elegant-circles/

**Git repo or how to get the list of icons**: https://github.com/dohliam/elegant-circles

**Additional info**: Elegant Themes Circle Icons in SVG format

**Comment by fileformat** [comment]
Added!  Thanks!
https://iconsear.ch/sources/elegantcircles/index.html
